### ISSUE TITLE
Support PEP 498 Literal String Interpolation (3.6+)

### ISSUE THREAD

**Issue by soupytwist** [google/pasta#35]
https://www.python.org/dev/peps/pep-0498/

There may be names referenced in fstrings that have to change as part of a refactoring. Pasta should be able to help with this, at least detecting where they are used.

**Comment by tapaswenipathak** [comment]
Hi @soupytwist: Can I work on the ticket?

**Comment by soupytwist** [comment]
Hi, I'd welcome the help! This one's actually mostly done though, in the sense that I don't have specific things left to do to support this. I think I can close this ticket, but please do feel free to pick up any other you like.
