### ISSUE TITLE
Missing support for relative imports over direct ancestor

### ISSUE THREAD

**Issue by mmv** [google/pasta#56]
✔ Works:
```
import pasta
tree = pasta.parse('from .uncle.package import foo')
```
✔ Works:
```
import pasta
tree = pasta.parse('from ..granduncle.package import foo')
```
❌ Fails:
```
import pasta
tree = pasta.parse('from ...greatgranduncle.package import foo')
```
with error `AnnotationError: Expected '.' but found '...'`

**Comment by soupytwist** [comment]
Seems to affect python3 only, my guess is that the py2 tokenizer splits the level into three separate `.` tokens but py3 combines them into one.

Thanks for reporting! Will have a fix soon.
