### ISSUE TITLE
Missing support for Python3 features

### ISSUE THREAD

**Issue by soupytwist** [google/pasta#58]
These AST nodes are not supported and can cause parse failures:

- [x] Constant
- [x] JoinedStr/FormattedValue
- [x] YieldFrom
- [x] AsyncFunctionDef
- [x] AsyncFor
- [ ] AsyncWith

Will update this list as support is added.

**Comment by mmv** [comment]
Also missing support for [PEP 448 - Additional Unpacking Generalizations](https://docs.python.org/3/whatsnew/3.5.html#pep-448-additional-unpacking-generalizations)

For example `merged = {**a, **b}` fails with a cryptic error

      File "pasta/base/annotate.py", line 804, in visit_Dict
        self.visit(key)
      File "pasta/base/annotate.py", line 1189, in visit
        fmt.set(node, 'indent', self._indent)
      File "pasta/base/formatting.py", line 37, in set
        _formatting_dict(node)[name] = value
      File "pasta/base/formatting.py", line 53, in _formatting_dict
        return getattr(node, PASTA_DICT)
    AttributeError: 'NoneType' object has no attribute '__pasta__'

because the node `key` in `visit_Dict` will be `None`

**Comment by soupytwist** [comment]
> Also missing support for [PEP 448 - Additional Unpacking Generalizations](https://docs.python.org/3/whatsnew/3.5.html#pep-448-additional-unpacking-generalizations)

Thanks, split this into #64 to limit the scope of this bug.

**Comment by tapaswenipathak** [comment]
Hi folks: Can I take adding `YieldFrom`?

**Comment by soupytwist** [comment]
> Hi folks: Can I take adding `YieldFrom` or is the ticket internal?

Please do!

**Comment by tapaswenipathak** [comment]
@soupytwist: Is there a channel where I can ask few questions or would you be ok w/ I creating a draft PR and you having a look if I understand well architecture wise?

**Comment by soupytwist** [comment]
I don't have a good channel for it, no. Feel free to send a draft PR for review or ask anything here. I've been meaning to add some instructions on testing locally, will do that today.

**Comment by soupytwist** [comment]
These have all been addressed already.
