### ISSUE TITLE
Bad indentation when rewriting funcion body

### ISSUE THREAD

**Issue by cript0nauta** [google/pasta#62]
Hi! I'm using your library in a toy project to change the body of some functions. When I change it and dump the modified ast, the code isn't indented right, so executing the dumped code will cause a SyntaxError.

Here is an example script that describes the issue:

```python
import ast
import pasta

source_code = '''
def test():
    return 5
'''

class SampleTransformer(ast.NodeTransformer):
    def visit_FunctionDef(self, node):
        node.body = [ast.copy_location(ast.Pass(), node.body[0])]
        return node

tree = pasta.parse(source_code)
SampleTransformer().visit(tree)

print pasta.dump(tree)
```

When I run it, I get the following output:

```python
def test():
pass
```

Instead of what I expected, that has proper indentation:

```python
def test():
    pass
```

I read that there is a known issue related to changing the indentation level of a block, but I think this is another (but maybe related) issue.

**Comment by soupytwist** [comment]
Sorry, I missed the report for this. Thank you for including the steps to reproduce, it made it much easier to track down this bug!

**Comment by cript0nauta** [comment]
Thanks for the fix! I tested the example python code in the issue again, and the dumped code has a valid indentation, so it doesn't raises SyntaxError's. However, the new code is indented with 2 spaces instead of 4. I was expecting this:

```python
def test():
    pass
```

but got this instead:

```python
def test():
  pass
```

The problem seems to be caused because the children doesn't have an indent attribute, so the `indented` function enters in this if statement:

```python
    new_diff = fmt.get(children[0], 'indent')
    if new_diff is None:
      new_diff = '  '
```

Which uses 2 space indentation instead of 4.

My whole codebase is indented with 4 spaces, so I have no problem with changing the `new_diff` to use 4 spaces and then solve the issue. But maybe the project should handle this in another way. It is up to you.

**Comment by soupytwist** [comment]
Quite right, I created #68. I thought of this when working on that fix, but was mostly focused on just making sure the syntax is correct (not necessarily consistent with the style).
