### ISSUE TITLE
Incomplete handling of complex f-strings

### ISSUE THREAD

**Issue by kriskorrel-cw** [google/pasta#65]
Pasta, which is required for the tf_upgrade_v2 script of Tensorflow, throws an error on a specific f-string. I believe support for f-strings has been added recently, but this seems to be incomplete.

This concerns the following minimal code example
```
import os
path = ["path", "to", "file"]
c = f"/{(os.sep).join(path)}"
```
When running `tf_upgrade_v2` (`pip3 install tensorflow==tensorflow==2.0.0-alpha0`)

Related: https://github.com/google/pasta/pull/61, https://github.com/google/pasta/pull/58, https://github.com/google/pasta/pull/59, https://github.com/tensorflow/tensorflow/issues/26486

**Comment by soupytwist** [comment]
Oops, I saw the bug in TF first. It's fixed in f26107d. Thanks!
