### ISSUE TITLE
f-strings over multiple lines

### ISSUE THREAD

**Issue by kriskorrel-cw** [google/pasta#66]
Thanks for fixing issue #65 ! 
I still have one file in my project though that I can't upgrade to Tensorflow 2.0 because of a new fstring-related error. There is no Tensorflow in this file, so I could just upgrade the project without this file, but maybe there are others experiencing the same issue.

The problem arises in the following setting:
I'm writing html/css code to a file, using strings that are split over multiple lines.
In addition to this, some strings are formatted using f-strings.
So as a minimal example, this is what it could look like:
```python
with open("test.out", "w") as f:
	a = 1
	f.write(f"{a}"
                 "{"
		 "}")
```
I believe the problem lies in the fact that the first string is an f-string. The second string is not, but is treated like one. Thus the opening bracket causes an issue.

**Comment by soupytwist** [comment]
Oh, interesting case. Thanks for reporting it, I believe you are right about the root cause. Will work on a fix.

Thanks!

**Comment by goelakash** [comment]
Hi, I've faced the same issue while trying to use the parse function on f-strings (similar to the example above).
Is the bug-fix simple, because I'm thinking of implementing that and opening a PR if that works out fine?

**Comment by soupytwist** [comment]
Tbh I'm not sure what the fix will involve. I'll take a stab at this since it's affecting multiple people -- thought it seemed pretty unlikely at the time.

**Comment by soupytwist** [comment]
Another case to reproduce this issue:

```python
pasta.parse("""
(f'a={a}'
 ' b={b}')
""")
```
