### ISSUE TITLE
Fails to parse usages of metaclass

### ISSUE THREAD

**Issue by timokau** [google/pasta#79]
I tried to use the tensorflow update script on a codebase that uses abstract classes with `ABCMeta`. Parsing failed with

```
AnnotationError: Expected ':' but found 'metaclass'
```

Minimal example:

```
pasta.parse('class A(metaclass=X): pass')    
```

**Comment by soupytwist** [comment]
This is some missing support for python3 syntax-- I'll add it. Thanks for the report and example!

**Comment by soupytwist** [comment]
Fixed at HEAD, I'll create a new version soon. Thanks again!

**Comment by timokau** [comment]
Wow, that was fast. Thank you!
